### ISSUE TITLE
Custom default colors

### ISSUE THREAD

**Issue by tupui** [Simulation-Decomposition/simdec-python#11]
> Excellent, thanks, @tupui! This way is even better. Can we set the default colors as these? 
{'#DC267F'; '#E8EA2F'; '#26DCD1';'#C552E4';'#3F45D0'} 
(first should go to the low-low-low scenario)

_Originally posted by @gnopik in https://github.com/Simulation-Decomposition/simdec-python/issues/10#issuecomment-1766281980_

**Comment by tupui** [comment]
`SEQUENTIAL_PALETTES` could either be a list of `str` or `mpl.colors.LinearSegmentedColormap` (using `colormap_from_single_color`). Then we just need to update the `cmaps` logic in `palette` to take that into account.

**Comment by gnopik** [comment]
@tupui, for decomposition with 3 variables the default colors are too close to each other (screenshot #1). 
When repainted, looks fine (screenshot #2). Can we have the second color palette blue-ish as in the case of two variables for decomposition (screenshot #3)?

Checked on different datasets, the same. 

![image](https://github.com/Simulation-Decomposition/simdec-python/assets/37065157/4904d720-7433-4d43-b249-530c49e17097)

![image](https://github.com/Simulation-Decomposition/simdec-python/assets/37065157/090cd5e7-293a-4236-bc30-62598f031402)

![image](https://github.com/Simulation-Decomposition/simdec-python/assets/37065157/b789224d-9809-4efe-9a5f-ad54f4fac495)

**Comment by tupui** [comment]
Yeah I've seen that. I need to understand what is happening because I would expect "Oranges" and then "Purples". Not "Reds".

**Comment by tupui** [comment]
All fixed with https://github.com/Simulation-Decomposition/simdec-python/commit/9d116996ab6a87cb8c11d129f014a3c4cb14f719 and a50c803ca88153e6ab5513b94f6325cc29952adb
