### ISSUE TITLE
Switch color order in the picker

### ISSUE THREAD

**Issue by gnopik** [Simulation-Decomposition/simdec-python#12]
Suggestion to reverse the order of main colors in the color picker from low to high, so it would coincide with the order in the Scenario table. (would be a bit more intuitive when playing with them) 

![image](https://github.com/Simulation-Decomposition/simdec-python/assets/37065157/616b2664-32fa-4a22-aa0a-d408208e5757)

**Comment by tupui** [comment]
Fixed in https://github.com/Simulation-Decomposition/simdec-python/commit/1851432bc28a0420aad2e118f035ccf5b96dc942
