### ISSUE TITLE
Favicon for dashboard

### ISSUE THREAD

**Issue by gnopik** [Simulation-Decomposition/simdec-python#13]
Do we want to have a custom favicon? This one is used in the simdec.fi. Any better ideas?
![image](https://github.com/Simulation-Decomposition/simdec-python/assets/37065157/e3b9986e-1135-40fc-90e4-0f24bc7e53cc)

**Comment by tupui** [comment]
Thanks I will replace the one I had with that.

FYI we have one but just on the login page. I need to override the other template to change the other page.
