### ISSUE TITLE
Links open in a new tab

### ISSUE THREAD

**Issue by gnopik** [Simulation-Decomposition/simdec-python#14]
Can we open links from the buttons on Dashboard in a new window/tab?
Otherwise, at least for now, all results are lost and one needs to redo all decomposition from scratch.
![image](https://github.com/Simulation-Decomposition/simdec-python/assets/37065157/2dfbeedb-f74a-4cb8-bc01-fef6df168534)

**Comment by tupui** [comment]
I just pushed an update for that 👍
