### ISSUE TITLE
Y-axis direction in box plots

### ISSUE THREAD

**Issue by gnopik** [Simulation-Decomposition/simdec-python#19]
The numeration on Y-axis does not match the scenario indices in the legend. 
![image](https://github.com/Simulation-Decomposition/simdec-python/assets/37065157/85f14fa6-e6fd-4dd8-a0f7-3ae697bd6bec)

**Comment by tupui** [comment]
Ark yes 👍

**Comment by tupui** [comment]
Fixed with https://github.com/Simulation-Decomposition/simdec-python/commit/4e87e4416342bf8576f47abe43ffcc3dde7811c2
