### ISSUE TITLE
The order of colors on dashboard

### ISSUE THREAD

**Issue by gnopik** [Simulation-Decomposition/simdec-python#28]
(Might be originating from fixing this issue: https://github.com/Simulation-Decomposition/simdec-python/issues/26)

The order of colors and their correspondence between legend and the left panel for color selection are wrong. 
Suggestion to have in both:

- Red for low
- Yellow for medium, and
- Blue for high

![image](https://github.com/Simulation-Decomposition/simdec-python/assets/37065157/ca4b7ef6-7582-4b06-9859-ccd6d0cbb52b)

**Comment by tupui** [comment]
Ark again, should be fixed now with https://github.com/Simulation-Decomposition/simdec-python/commit/50246f8492382e8090882885e9f877adc3b56607

**Comment by tupui** [comment]
Though I did not put red as low. Just forgot, do you want it? The issues themselves (wrong labelling and slightly diff colour) should be fixed.

**Comment by gnopik** [comment]
The correspondence (legend-color selector) is good now! 
Yes, let's have red as low, yellow as medium and blue as high?

**Comment by tupui** [comment]
Done in 49e3b671a9434329fd3c91e32d33bc3e8a4392ba
