### ISSUE TITLE
X-axis limits

### ISSUE THREAD

**Issue by gnopik** [Simulation-Decomposition/simdec-python#29]
Would it be possible/easy to give the user an input for X-axis limits in the dashboard? That would allow fair comparison of different outputs and more decent scientific reporting. 
The axis limits should affect both, histogram and box plots. 
And the input area can be placed just under the number of bins slicer.

**Comment by tupui** [comment]
Done in e78e7bfea55ab63b2464094b743330af99892b27

**Comment by gnopik** [comment]
Cool! Would it make sense to add rounding to numbers? 
![image](https://github.com/Simulation-Decomposition/simdec-python/assets/37065157/cf2fdc09-e44c-4860-a90f-6ed832373deb)

**Comment by gnopik** [comment]
Yes, makes sense.
