### ISSUE TITLE
Long time to update Output field

### ISSUE THREAD

**Issue by gnopik** [Simulation-Decomposition/simdec-python#3]
When a new dataset is loaded, all fields quickly get filled. e.g. Input selector and multichoice for decomposition, but the **Output** field is stuck for a while with the list of variables from the previous dataset.

**Comment by tupui** [comment]
That was an interesting one 😅 It was just the UI taking some time to refresh. There is an inconsistency in Panel's API. Fixed with https://github.com/Simulation-Decomposition/simdec-python/commit/6417d49fdf1863151bcd459e803f952438e50558
