### ISSUE TITLE
X lim do not scale for new data

### ISSUE THREAD

**Issue by gnopik** [Simulation-Decomposition/simdec-python#30]
When new data is uploaded, X-axis limits remain from the previous case, which might cause awfully scaled graph (or even all data off the graph). That would be especially harsh for newcomers :( 
![image](https://github.com/Simulation-Decomposition/simdec-python/assets/37065157/d0698a2d-75a7-4d93-95bf-f5a08865c2ea)

**Comment by gnopik** [comment]
can't it just check min and max values of the output and scale the graph accordingly when data is loaded first time?

**Comment by tupui** [comment]
The issue is with the way the sliders work. Sliders and all these UI elements are hard to make react to changing data. When it loads the first time, some code gets executed to give the values for the sliders. I need to see if I can re-initialize it when loading a new file.

**Comment by gnopik** [comment]
If automatic re-initialization is too hard to get, how about another button "Reset" there?

**Comment by tupui** [comment]
Fix in https://github.com/Simulation-Decomposition/simdec-python/commit/80e977cfaf4c8e419129117708f397c21096d83e
