### ISSUE TITLE
Adding an example usage to documentation

### ISSUE THREAD

**Issue by matt-graham** [Simulation-Decomposition/simdec-python#31]
Raising as part of JOSS review openjournals/joss-reviews/issues/6713

It would help users to have one or more example sin the documentation (or top-level README) of using `simdec` to compute sensitivity indices / visualize the results. This could potentially use the same data already used in the tests.

**Comment by tupui** [comment]
Closing in favour of #34

**Comment by matt-graham** [comment]
Just to note that having an example usage in the _documentation_ (not the JOSS paper) is a specific requirement JOSS reviewers are asked to check in their checklist

> Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

If the intention of closing this in favour of #34 is that you'll still include an example usage in the documentation (of reproducing the figure from JOSS paper) that's fine but otherwise I would say this should be reopened.
