### ISSUE TITLE
two-output & scatterplot

### ISSUE THREAD

**Issue by gnopik** [Simulation-Decomposition/simdec-python#37]
Things we need to realize for the two-output analysis:

1. **switch** to two outputs
2. **selection box** for the second output
3. **scatterplot**
4. reduction of points **slicer** (e.g. every 100th row) to avoid overcrowding 
5. SimDec histograms on the sides

Example:
![image](https://github.com/Simulation-Decomposition/simdec-python/assets/37065157/4d395369-ab7e-4b17-a742-9407dbd5a30a)

Possible solutions for point 5:
https://seaborn.pydata.org/generated/seaborn.jointplot.html
https://seaborn.pydata.org/generated/seaborn.pairplot.html
https://seaborn.pydata.org/generated/seaborn.rugplot.html#seaborn.rugplot

**Comment by tupui** [comment]
Fixed with 2b29d10629420d35898d4d09d7838437e3adcdb5 (and previous commits.)
