### ISSUE TITLE
 Download results

### ISSUE THREAD

**Issue by gnopik** [Simulation-Decomposition/simdec-python#5]
Let's have a button to download numeric results from the dashboard. Would be great if the csv file contained:

1. sensitivity indices - FOE, SOE, SI
2. scenario table (legend)
3. input states boundaries

**Comment by tupui** [comment]
For my reference: https://panel.holoviz.org/reference/widgets/FileDownload.html

@gnopik do you want a single csv? If yes I am not sure about the column names there.

**Comment by gnopik** [comment]
Good question. Perhaps it would make more sense as separate files:
1. Scenario table
2. States
3. Sensitivity indices.
And perhaps sensitivity indices is also wise to break into three:
3.1. First-order effects
3.2. Second-order effects
3.3. Combined sensitivity indices

@tupui, does sit make sense? 

And then we have five different files. Should they be in an archive?

**Comment by tupui** [comment]
There is a central question to answer first to me. The format.

If we are flexible, we can go with more modern format like parquet files (see this for instance https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#parquet) or JSON.

This way we can be very "expressive".

**Comment by gnopik** [comment]
@tupui, the csv download works well!  
In the first SI table, there are two (almost duplicate) columns of numeric data, would it make sense to have just the second one?
Otherwise the structure is great! 

![image](https://github.com/Simulation-Decomposition/simdec-python/assets/37065157/0a0e6cde-6850-491d-9f9a-5b1432985225)

**Comment by tupui** [comment]
Sure I can 👍😅 While I am at it, I will remove the index and extra 0.

**Comment by tupui** [comment]
Fixed in https://github.com/Simulation-Decomposition/simdec-python/commit/315c6270cc28225714b693f9a5a001ee98dcd581
