### ISSUE TITLE
Order of colors in boxplot

### ISSUE THREAD

**Issue by gnopik** [Simulation-Decomposition/simdec-python#9]
The order of boxes is good, but the order of colors is reversed in the box plot (the entire order, both main colors and shades). It needs to preserve the order of boxes but flip the order of colors.  
![image](https://github.com/Simulation-Decomposition/simdec-python/assets/37065157/0b2055d9-ab26-4ca3-a905-47d22418a9a8)

**Comment by tupui** [comment]
Ah yes, I pushed a fix 👍
